"""Export the lookup tables the extension needs into a JavaScript module.

The extension can now do the whole search-decode-annotate pipeline itself when
the daemon is not running, which means the pipeline exists twice. The *logic*
being written twice is unavoidable and is covered by a parity test; the *data*
being written twice is avoidable, and that is what this script is for.

It matters most for `_STEM_SYMBOLS`, which is two hundred and fifty odd entries
that grew from measurement against a corpus of real caption files. Hand-copying
it would guarantee drift, and drift would be silent: the JavaScript side would
keep matching, just slightly worse, and nothing would fail.

Reading the tables out of the imported module also settles the duplicate keys
the Python source contains - `clatter` is listed under both 💥 and 🍽️ - the
same way Python does, last one wins. A hand copy would have to notice.

    uv run python tools/export_tables.py

The result is checked in. `tests/test_generated_tables.py` regenerates it and
fails if it differs, so a table edit that skips this script is caught.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from subtitle_daemon import annotations, cache, markup, matching, subtitles  # noqa: E402

OUTPUT = (
    Path(__file__).resolve().parents[2]
    / "browser-extension"
    / "src"
    / "subtitles"
    / "tables.generated.js"
)

HEADER = """\
/* Generated by subtitle-daemon/tools/export_tables.py - do not edit.
 *
 * The daemon and the extension run the same pipeline in two languages. The
 * logic is written twice and kept honest by a parity test; the data is written
 * once, here, and copied. Edit the Python tables and re-run the script.
 */

"""


def js_value(value: object) -> str:
    """Render a Python value as JavaScript. JSON is a subset, so this is it."""
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=False)


def sorted_set(values: object) -> list[str]:
    """Frozensets have no order; sorting gives the file a stable diff."""
    return sorted(values)  # type: ignore[call-overload]


def build() -> str:
    exports: list[tuple[str, object]] = [
        # annotations.py
        ("PHRASE_SYMBOLS", annotations._PHRASE_SYMBOLS),
        ("STEM_SYMBOLS", annotations._STEM_SYMBOLS),
        ("MUSIC_MOOD", sorted_set(annotations._MUSIC_MOOD)),
        ("MUSIC_UPBEAT", sorted_set(annotations._MUSIC_UPBEAT)),
        ("GENERIC_SPEAKERS", sorted_set(annotations._GENERIC_SPEAKERS)),
        ("MODIFIERS", sorted_set(annotations._MODIFIERS)),
        ("NOUN_STEMS", sorted_set(annotations._NOUN_STEMS)),
        ("SOUND_COLOR", annotations.SOUND_COLOR),
        ("MUSIC_COLOR", annotations.MUSIC_COLOR),
        ("SPEAKER_PALETTE", list(annotations.SPEAKER_PALETTE)),
        # markup.py
        ("TAG_NAMES", markup._TAG_NAMES),
        ("NAMED_COLORS", sorted_set(markup._NAMED_COLORS)),
        ("VERTICAL_BY_ALIGNMENT", {str(k): v for k, v in markup._VERTICAL_BY_ALIGNMENT.items()}),
        # matching.py
        ("AUTO_ATTACH_THRESHOLD", matching.AUTO_ATTACH_THRESHOLD),
        ("VISIBLE_THRESHOLD", matching.VISIBLE_THRESHOLD),
        ("ARTICLES", sorted_set(matching._ARTICLES)),
        # subtitles.py
        ("CANDIDATE_ENCODINGS", list(subtitles._CANDIDATE_ENCODINGS)),
        # cache.py - the extension keeps its own store in IndexedDB, but the two
        # have to agree on what a search key means and when it goes stale, or a
        # cached answer would survive on one side of the sync and not the other.
        ("SEARCH_TTL_SECONDS", cache.SEARCH_TTL_SECONDS),
        ("SEARCH_SCHEMA_VERSION", cache.SEARCH_SCHEMA_VERSION),
    ]

    parts = [HEADER]
    for name, value in exports:
        parts.append(f"export const {name} = {js_value(value)};\n\n")
    return "".join(parts).rstrip("\n") + "\n"


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
