/* How rare is this word, in film dialogue.
 *
 * Runs in the service worker rather than in the page. The tables are a quarter
 * of a megabyte each and the content script is injected into every frame of
 * every tab, so holding them there would multiply that by the number of frames
 * open - to answer a question that arrives twenty times a minute and takes a
 * map lookup. One copy behind a message is the cheaper shape by a wide margin,
 * and the worker being torn down and restarted only costs a re-parse.
 *
 * Tables are generated by tools/build-frequency.mjs. See that file for why the
 * OpenSubtitles corpus is the right one to rank against.
 */

import { letGo } from "../http.js";

/* Loaded on first use, not at worker startup: most sessions never turn study
 * mode on, and paying a quarter of a megabyte of parse for them would slow down
 * the thing everybody does use - attaching a subtitle. */
const tables = new Map();
const loading = new Map();

/** Rank tables ship per language; anything else has no answer to give. */
export const SUPPORTED = ["en", "tr"];

/* Fetched as text, not imported as a module, and that is the whole reason this
 * feature worked in the harness and never once in a browser.
 *
 * The tables used to be `.generated.js` behind `import(...)`, which reads as
 * the obvious way to load something lazily. A service worker is the one place
 * it cannot be: the HTML specification disallows dynamic import on
 * ServiceWorkerGlobalScope (w3c/ServiceWorker#1356), so every call threw
 * `TypeError: import() is disallowed`. Measured in a loaded extension: EN and
 * TR both, on the first word of the first cue.
 *
 * The throw was caught and written down as "this language has no table", so
 * study mode said "No word-frequency list for EN, so nothing is marked
 * automatically" and stopped asking for the rest of the session. Both shipped
 * languages, every session - the focus box was correctly built, correctly
 * placed and permanently empty, and the sentence inside it blamed the data.
 *
 * fetch on a packaged file needs no web_accessible_resources entry: that gates
 * pages and content scripts, not the extension's own worker. */
async function table(language) {
  const lang = normaliseLanguage(language);
  if (!lang) return null;
  if (tables.has(lang)) return tables.get(lang);

  if (!loading.has(lang)) {
    loading.set(
      lang,
      load(lang)
        .then((ranks) => {
          tables.set(lang, ranks);
          return ranks;
        })
        /* Not cached as a failure, and not swallowed.
         *
         * A language with no table is answered above, before anything is
         * loaded, so everything that reaches here is a table that ships and
         * would not load - which is a defect, never a fact about the language.
         * Letting it out means the surface says something is wrong instead of
         * quietly promising rare words for two hours; not remembering it means
         * the next cue tries again rather than the session being lost to one
         * bad fetch. */
        .finally(() => loading.delete(lang)),
    );
  }
  return loading.get(lang);
}

async function load(lang) {
  const url = chrome.runtime.getURL(`src/study/frequency-${lang}.generated.txt`);
  const response = await fetch(url);
  if (!response.ok) {
    letGo(response);
    throw new Error(`frequency table for ${lang}: HTTP ${response.status}`);
  }
  const ranks = new Map();
  // Rank is the line number, so the split has to keep every line but the
  // trailing empty one the file ends with.
  const words = (await response.text()).split("\n");
  if (words[words.length - 1] === "") words.pop();
  if (words.length === 0) throw new Error(`frequency table for ${lang} is empty`);
  words.forEach((word, rank) => ranks.set(word, rank));
  return ranks;
}

function normaliseLanguage(language) {
  const lang = String(language || "").toLowerCase().slice(0, 2);
  return SUPPORTED.includes(lang) ? lang : null;
}

/* Contractions and possessives are not in the tables: the corpus was tokenised
 * on the apostrophe, so it holds "don" and "we" but never "don't" or "we'll".
 * Without this every contraction in the film - which is most of the dialogue -
 * would be absent from the table, and absent means rare. Falling back to the
 * part before the apostrophe gets the right answer for English contractions and
 * possessives, and for the Turkish suffixed proper nouns ("Ankara'ya"), which
 * are the same shape. */
function ranked(ranks, raw) {
  /* Composed first, because the table is composed and a subtitle file need not
   * be. A .srt saved in NFD writes "ışık" as five code points, the s carrying a
   * separate COMBINING CEDILLA, and lowercasing does not put it back together -
   * so the word reached the table in a form the table does not hold, came back
   * absent, and absent counts as rarer than the last word in the file.
   * Measured: the decomposed spelling answered null where the composed one
   * answers 1626. The dotted i is a different problem and is already handled
   * where the words are folded, in study.js - NFC does not compose i + U+0307,
   * because there is no single code point for it. */
  const word = raw.normalize("NFC");
  const direct = ranks.get(word);
  if (direct !== undefined) return direct;
  const apostrophe = word.search(/['’]/);
  if (apostrophe > 0) {
    const stem = ranks.get(word.slice(0, apostrophe));
    if (stem !== undefined) return stem;
  }
  return null;
}

/**
 * Rank each word, or null for "not in the table at all", which is rarer than
 * anything the table holds.
 *
 * Returns a plain object because this crosses a message boundary, where a Map
 * does not survive.
 */
export async function rank(words, language) {
  const ranks = await table(language);
  /* No prototype to collide with. The word pattern in study.js cannot produce
   * "__proto__" - it matches letters, marks, apostrophes and hyphens - so this
   * is not a defect anyone has hit; it is that `rank` is reached by a message
   * whose word list this file does not get to choose, and on a plain object
   * that one word would set the prototype instead of an entry. */
  const out = Object.create(null);
  if (!ranks) return out;
  for (const word of words) out[word] = ranked(ranks, word);
  return out;
}
