/* How rare is this word, in film dialogue.
 *
 * Runs in the service worker rather than in the page. The tables are a quarter
 * of a megabyte each and the content script is injected into every frame of
 * every tab, so holding them there would multiply that by the number of frames
 * open - to answer a question that arrives twenty times a minute and takes a
 * map lookup. One copy behind a message is the cheaper shape by a wide margin,
 * and the worker being torn down and restarted only costs a re-parse.
 *
 * Tables are generated by tools/build-frequency.mjs. See that file for why the
 * OpenSubtitles corpus is the right one to rank against.
 */

/* Loaded on first use, not at worker startup: most sessions never turn study
 * mode on, and paying a quarter of a megabyte of parse for them would slow down
 * the thing everybody does use - attaching a subtitle. */
const tables = new Map();
const loading = new Map();

/** Rank tables ship per language; anything else has no answer to give. */
export const SUPPORTED = ["en", "tr"];

async function table(language) {
  const lang = normaliseLanguage(language);
  if (!lang) return null;
  if (tables.has(lang)) return tables.get(lang);

  if (!loading.has(lang)) {
    loading.set(
      lang,
      import(`./frequency-${lang}.generated.js`)
        .then((module) => {
          const ranks = new Map();
          module.WORDS.split("\n").forEach((word, rank) => ranks.set(word, rank));
          tables.set(lang, ranks);
          return ranks;
        })
        .catch(() => {
          // A missing table is "no opinion", never a broken feature: study mode
          // still marks nothing and everything else keeps working.
          tables.set(lang, null);
          return null;
        })
        .finally(() => loading.delete(lang)),
    );
  }
  return loading.get(lang);
}

function normaliseLanguage(language) {
  const lang = String(language || "").toLowerCase().slice(0, 2);
  return SUPPORTED.includes(lang) ? lang : null;
}

/* Contractions and possessives are not in the tables: the corpus was tokenised
 * on the apostrophe, so it holds "don" and "we" but never "don't" or "we'll".
 * Without this every contraction in the film - which is most of the dialogue -
 * would be absent from the table, and absent means rare. Falling back to the
 * part before the apostrophe gets the right answer for English contractions and
 * possessives, and for the Turkish suffixed proper nouns ("Ankara'ya"), which
 * are the same shape. */
function ranked(ranks, word) {
  const direct = ranks.get(word);
  if (direct !== undefined) return direct;
  const apostrophe = word.search(/['’]/);
  if (apostrophe > 0) {
    const stem = ranks.get(word.slice(0, apostrophe));
    if (stem !== undefined) return stem;
  }
  return null;
}

/**
 * Rank each word, or null for "not in the table at all", which is rarer than
 * anything the table holds.
 *
 * Returns a plain object because this crosses a message boundary, where a Map
 * does not survive.
 */
export async function rank(words, language) {
  const ranks = await table(language);
  const out = {};
  if (!ranks) return out;
  for (const word of words) out[word] = ranked(ranks, word);
  return out;
}
